spring:
  profiles:
    active: dev
    include: secret
  autoconfigure:
    exclude: # 레디스 디펜던시들이 로컬 환경에서 작동하지 않고 운영환경에서만 작동
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./health_dev;MODE=MYSQL # DB : TdM_dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 100
          format_sql: true
          highlight_sql: true
          use_sql_comments: true
  thymeleaf:
    cache: false
    mvc:
      hiddenmethod:
        filter:
          enabled: true
  logging:
    level:
      com.ll.healthweb: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE
  custom:
    site:
      name: Health-web
      baseUrl: "http://localhost:${server.port}"